### PR TITLE
Multiple commits. See separate commit messages.

### PR DESCRIPTION
**Pull request by thohell**
* Updated .toc for building clean nolib packages
* Removed embeds.xml. It should not be needed(?)

### CODE REVIEW

**Comment by thohell** [comment]
bild

**Comment by thohell** [comment]
Tested on Classic, Retail & Retail [nolibs] without any issues

**Comment by doadin** [comment]
Nice looking good.

**Comment by thohell** [comment]
Started refactoring out filters. Fixed a bug in the EquipmentSet filter:

BUG:
bild

FIXED:
bild

**Comment by doadin** [comment]
Other than the few comments I have made so far(which I can address myself once you are close to done here?) its looking really good. Which idk if you wana let me know when your closer to done with this set of commits and then ill close this one out and can start another?

**Comment by thohell** [comment]
I am far from done, but as far as I am concerned each commit is self
contained and should never rely on later commits (unless I make a boo-boo,
in which case I hope to catch it before you approve). You can go ahead and
close and pr's that looks OK, and I'll just open a new one as soon as new
code is ready.

:)

Den tis 5 maj 2020 21:37doadin <notifications@github.com> skrev:

**Comment by doadin** [comment]
I think what im going to do is test in game these changes and close this out, address the few things in my comments then merge all those changes. For the moment im going to close this(as a code freeze), ill add my changes to it over then next few min.

**Comment by doadin** [comment]
@thohell I think i have addressed this now.

**Comment by doadin** [comment]
@thohell It does appear this commit is also affecting luacheck build status, though its usefulness is questionable anyways.

**Comment by thohell** [comment]
I didn't run luacheck locally, but I saw your latest commit. It seems strange that release.sh is misbehaving like that. I build locally using release.sh, and the tags expand correctly to both retail and classic. 

As per the repo, this should be the correct way to do it:
bild

ie. Wrap retail code in --@retail@ / --@end-retail@ and classic code in --[===[@non-retail@ / --@end-non-retail@]===]

**Comment by thohell** [comment]
Looking at the build artifacts from 3.3.0-beta, the substitution seems correct:
Classic:
bild

Retail:
bild

**Comment by doadin** [comment]
yea after the change i think i might have had it reversed retail isnt working classic is. When i loaded into classic i had gotten an error saying expected end looked and saw that there where two if s neither commented out with one with retail around it one with not. One use is wrong i guess i guessed at the wrong one.

**Comment by thohell** [comment]
The build artifacts for 3.3.1-beta seems a bit wonky for retail :D 

Classic:
bild

Retail:
bild

**Comment by doadin** [comment]
I think im going to just revert its use.

**Comment by thohell** [comment]
> 
> 
> yea after the change i think i might have had it reversed retail isnt working classic is. When i loaded into classic i had gotten an error saying expected end looked and saw that there where two if s neither commented out with one with retail around it one with not. One use is wrong i guess i guessed at the wrong one.

Which file and line number? I can look at it real quick

**Comment by doadin** [comment]
Baggins_ItemOps.lua@140

**Comment by doadin** [comment]
I think thats the spot anyways the error was expected end to close function at line 103

**Comment by thohell** [comment]
> 
> 
> Baggins_ItemOps.lua@140

Aaah! I made a typo!
Replace --@release@ / --@non-release@ => --@retail@ / --@non-retail@

**Comment by thohell** [comment]
Same typo also in Baggins-Filtering.lua @ lines 494 and 498

**Comment by doadin** [comment]
yea i did a search for release :P thanks!

**Pull request closed without merging**
